name: Build and Push Docker Image

on:
  push:
    branches:
      - refactor/rgavira  # O la rama que quieras (por ejemplo, develop)

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Loguearse en Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Reconstruct .env file
        run: |
          echo "${{ secrets.ENV_BASE64 }}" | base64 --decode > .env
        
      # 3. Construir la imagen con `latest`
      - name: Build Docker image
        run: |
          IMAGE_NAME=rgavira123/pricing4api
          docker build -f docker/Dockerfile.deepnote -t $IMAGE_NAME:latest .

      # 4. Subir la imagen al Docker Hub
      - name: Push Docker image
        run: |
          IMAGE_NAME=rgavira123/pricing4api
          docker push $IMAGE_NAME:latest
